name: Horusec Security Scan

on:
  push:
    branches:
      - '*'
#any branch
jobs:
  security_scan:
    runs-on: ubuntu-latest #github hosted runner

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Docker check
        run: docker --version
        

      - name: Install Horusec CLI
        run: |
          curl -fsSL https://github.com/ZupIT/horusec/releases/download/v2.9.0-beta.3/horusec_linux_amd64

      - name: Run Horusec Security Scan
        run: |
          horusec start -p="./" --config-file-path=./horusec-config.json -p=./ -o="json" -O="./horusec-output.json" -e="true"
