 name: Horusec Security Scan

 on:
  push:
    branches:
      - '*' #push to any branch
#triggering the event      

 jobs:
  security_scan:
    runs-on: ubuntu-latest  #runner
    #the part that gets executed everytime an event occurs
    steps:
   
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
       https://github.com/ZupIT/horusec/releases/download/v2.8.0/horusec_linux_amd64

        
    
