name: Horusec Security Scan

on:
  push:
    branches:
      - main
#triggering the event      

jobs:
  security_scan:
    runs-on: ubuntu-latest
    #the part taht gets executed everytime an event occurs
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
        curl https://github.com/ZupIT/horusec/releases/download/v2.9.0-beta.3/horusec_linux_amd64 -o horusec && chmod 777 ./horusec
    - name: Run Horusec Security Scan
      run: ./horusec generate && horusec start --config-file-path=./horusec-config.json --project-path=./ --output-format=json --output-path=./output.json
