 name: Horusec Security Scan

 on:
  push:
    branches:
      - '*' #push to any branch
#triggering the event      

 jobs:
  security_scan:
    runs-on: ubuntu-latest  #runner
    #the part that gets executed everytime an event occurs
    steps:
    - name: Check 
      run: uname -m 
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
        
    #
