name: Horusec Security Scan

on:
  push:
    branches:
      - main
      - master
      # Add other branches as needed

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Run Horusec Security Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            horuszup/horusec-cli:latest \
            start -p /src -o=json -O=./horusec-result.json
