name: Horusec Security Scan

on:
  push:
    branches:
      - '*' # Trigger on push to any branch

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Get Horusec CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh |  bash -s v2.9.0-beta.3


      - name: Run Horusec Security Scan
        run: |
          horusec generate && \
          horusec start -p="./" --config-file-path=./horusec-config.json \
          --project-path=./ --output-format=json --output-path=./horusec-output.json -e="true"

      - name: Upload Security Scan Report
        if: always() # Ensures the report is uploaded regardless of scan result
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: ./horusec-output.json
