name: Horusec Security Scan

on: [push]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Run Horusec Security Scan
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          horuszup/horusec-cli:latest \
          start -p /src -o="json" -O="./horusec-result.json"
