 name: Horusec Security Scan

 on:
  push:
    branches:
      - '*' #push to any branch
#triggering the event      

 jobs:
  security_scan:
    runs-on: ubuntu-latest  #runner
    #the part that gets executed everytime an event occurs
    steps:
    - name: Docker start
      run: sudo systemctl start docker
      
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
       curl -fsSL https://github.com/ZupIT/horusec/releases/download/v2.9.0-beta.3/horusec_linux_amd64
    - name: Run Horusec Security Scan
      run: horusec generate && horusec start -p="./" --config-file-path=./horusec-config.json -p=./ -o="json" -O="./output.json" -e="true"
        
    
