name: Horusec Security Scan

on:
  push:
    branches:
      - main
#triggering the event      

jobs:
  security_scan:
    runs-on: ubuntu-latest
    #the part that gets executed everytime an event occurs
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s v2.9.0-beta.3

    - name: Run Horusec Security Scan
      run: ./horusec generate && horusec start --config-file-path=./horusec-config.json --project-path=./ --output-format=json --output-path=./output.json
