name: Horusec Security Scan

# Defines when the action will run. 
on: 
  push:
    # Trigger the workflow on push events to any branch
    branches:
      - '**'

jobs:
  # This workflow contains a single job called "scan"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Horusec CLI
        run: |
          curl -fsSL https://horusec.io/bin/install.sh | bash

      # Runs the Horusec security scan
      - name: Run Horusec Security Scan
        run: |
          horusec start -p="./" -e="true"
v
