name: Horusec Security Scan

on:
  push:
    branches:
      - '*'
#any branch
jobs:
  security_scan:
    runs-on: ubuntu-latest #github hosted runner

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Docker check
        run: docker --version
        

      - name: Install Horusec CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
         
      - name: Run Horusec Security Scan
        run: |
          horusec start -p="./" -o="json" -O="./horusec"
