 name: Horusec Security Scan

 on:
  push:
    branches:
      - '*' #push to any branch
#triggering the event      

 jobs:
  security_scan:
    runs-on: ubuntu-latest  #runner
    #the part that gets executed everytime an event occurs
    steps:
    - name: Docker start
      run: sudo systemctl start docker
      
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: get horusec cli
      run: |
       curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
    - name: Run Horusec Security Scan
      run: horusec generate && horusec start -p="./" --config-file-path=./horusec-config.json --project-path=./ --output-format=json --output-path=./output.json -e="true"
        
    
